### ISSUE TITLE
Push is not working currently

### ISSUE THREAD

**Issue by lobcare** [lobcare/lobcare#4]
Anyone help me my push unworking

**Comment by lobcare** [comment]
I'm not familiar to Github. any one teach me how to push.

This is my issues
I'm going to push to new repository from existing one.
So I've used this steps : 
git remote add origin https://github.com/dontsayhello/Casual-Hyper-Unity.git
git branch -M main
git push -u origin main

But doesn't work

**Comment by dontsayhello** [comment]
I'm new to github too like you.
And I've follow the steps like you but working.

**Comment by winnerdev2012** [comment]
I see.. what you are getting at.
You are customize the readme file and make that to yours right?

You can try to follow this steps:
1.  find the config file in your .git folder.
2.  open the config file and and edit the url path like this image.
![image](https://github.com/lobcare/lobcare/assets/70522646/d3d5854a-74dd-4eb2-9247-141f7cbf0063)

**Comment by lobcare** [comment]
It was working. Thank you.

**Comment by winnerdev2012** [comment]
You are welcome
